// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using DBFIRST.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DBFIRST.Context
{
    public partial interface INorthwindContextProcedures
    {
        Task<int> DeleteEmployeeByIDAsync(int? employeeID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<int> DeleteProductByIDAsync(int? productId, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<DiscontinuedProductsResult>> DiscontinuedProductsAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SalesbyYearResult>> SalesbyYearAsync(DateTime? beginning_Date, DateTime? ending_Date, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SalesByCategoryResult>> SalesByCategoryAsync(string? categoryName, string? ordYear, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
        Task<List<SelectAllProductsResult>> SelectAllProductsAsync(OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default);
    }
}
